<?php


namespace Ehua\Rest\Fulu;

/**
 * 文档地址：https://docs.open.fulu.com/question2
 * 福禄API
 * Class Common
 * @package Fulu
 */
class Common
{
    public function __construct($debug = false, $cpnfig)
    {
        $this->app_key = $cpnfig['app_key'];
        $this->AppSecret = $cpnfig['token'];
        if ($debug) {
            $this->HOST = 'https://pre-openapi.fulu.com/api/getway';
        } else {
            $this->HOST = 'https://openapi.fulu.com/api/getway';
        }
    }

    public function http($data)
    {
        // Generated by ApiPost: https://www.apipost.cn/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $this->HOST);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }


    /**
     * php签名方法
     */
    protected function getSign($Parameters)
    {
        //签名步骤一：把字典json序列化
        $json = json_encode($Parameters, 320);
        //签名步骤二：转化为数组
        $jsonArr = $this->mb_str_split($json);
        //签名步骤三：排序
        sort($jsonArr);
        //签名步骤四：转化为字符串
        $string = implode('', $jsonArr);
        //签名步骤五：在string后加入secret
        $string = $string . $this->AppSecret;
        //签名步骤六：MD5加密
        $result_ = strtolower(md5($string));
        return $result_;
    }

    /**
     * 可将字符串中中文拆分成字符数组
     */
    protected function mb_str_split($str)
    {
        return preg_split('/(?<!^)(?!$)/u', $str);
    }
}