<?php


namespace Ehua\Weixin\Xcx;


class Common
{
    public function __construct($cpnfig)
    {
        $this->AppID = $cpnfig['AppID'];
        $this->AppSecret = $cpnfig['AppSecret'];
    }

    public function http($data)
    {
        // Generated by ApiPost: https://www.apipost.cn/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $this->HOST);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }
}